# Build settings
[build]
command = "npm run build"          # Command to build your Next.js app
publish = ".next"                  # Use the Next.js build output for SSR
functions = "netlify/functions"    # Directory for server-side rendering and API routes

# Netlify Next.js Plugin
[[plugins]]
package = "@netlify/plugin-nextjs" # Enables full Next.js support on Netlify